"""voice_marketplace_warroom

Revision ID: 2d975e254447
Revises: aeb5b371cdc2
Create Date: 2026-05-16 06:43:55.978287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d975e254447'
down_revision: Union[str, None] = 'aeb5b371cdc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('councillor_id', sa.UUID(), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required_count', sa.Integer(), nullable=True),
    sa.Column('reward_per_volunteer', sa.Integer(), nullable=True),
    sa.Column('urgency', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['councillor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volunteer_requests_councillor_id'), 'volunteer_requests', ['councillor_id'], unique=False)
    op.create_index(op.f('ix_volunteer_requests_id'), 'volunteer_requests', ['id'], unique=False)
    op.create_index(op.f('ix_volunteer_requests_ward_id'), 'volunteer_requests', ['ward_id'], unique=False)
    op.create_table('marketplace_acceptances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('volunteer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['volunteer_requests.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_acceptances_id'), 'marketplace_acceptances', ['id'], unique=False)
    op.create_index(op.f('ix_marketplace_acceptances_request_id'), 'marketplace_acceptances', ['request_id'], unique=False)
    op.create_index(op.f('ix_marketplace_acceptances_volunteer_id'), 'marketplace_acceptances', ['volunteer_id'], unique=False)
    op.add_column('complaints', sa.Column('voice_submitted', sa.Boolean(), nullable=True))
    op.add_column('complaints', sa.Column('audio_url', sa.String(), nullable=True))
    op.add_column('complaints', sa.Column('transcribed_text', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('war_room_mode', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'war_room_mode')
    op.drop_column('complaints', 'transcribed_text')
    op.drop_column('complaints', 'audio_url')
    op.drop_column('complaints', 'voice_submitted')
    op.drop_index(op.f('ix_marketplace_acceptances_volunteer_id'), table_name='marketplace_acceptances')
    op.drop_index(op.f('ix_marketplace_acceptances_request_id'), table_name='marketplace_acceptances')
    op.drop_index(op.f('ix_marketplace_acceptances_id'), table_name='marketplace_acceptances')
    op.drop_table('marketplace_acceptances')
    op.drop_index(op.f('ix_volunteer_requests_ward_id'), table_name='volunteer_requests')
    op.drop_index(op.f('ix_volunteer_requests_id'), table_name='volunteer_requests')
    op.drop_index(op.f('ix_volunteer_requests_councillor_id'), table_name='volunteer_requests')
    op.drop_table('volunteer_requests')
    # ### end Alembic commands ###
