"""add_complaint_details_and_volunteer_posts

Revision ID: 6b5da6826ed5
Revises: 
Create Date: 2026-05-15 05:38:19.192612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b5da6826ed5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('volunteer_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volunteer_posts_id'), 'volunteer_posts', ['id'], unique=False)
    op.create_index(op.f('ix_volunteer_posts_volunteer_id'), 'volunteer_posts', ['volunteer_id'], unique=False)
    op.add_column('complaints', sa.Column('photo_url', sa.String(), nullable=True))
    op.add_column('complaints', sa.Column('gps_lat', sa.Float(), nullable=True))
    op.add_column('complaints', sa.Column('gps_lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'gps_lng')
    op.drop_column('complaints', 'gps_lat')
    op.drop_column('complaints', 'photo_url')
    op.drop_index(op.f('ix_volunteer_posts_volunteer_id'), table_name='volunteer_posts')
    op.drop_index(op.f('ix_volunteer_posts_id'), table_name='volunteer_posts')
    op.drop_table('volunteer_posts')
    # ### end Alembic commands ###
