"""add_location_address

Revision ID: 88a05ce91917
Revises: 6b5da6826ed5
Create Date: 2026-05-15 06:41:17.844488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88a05ce91917'
down_revision: Union[str, None] = '6b5da6826ed5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('location_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'location_address')
    # ### end Alembic commands ###
