"""add_next_gen_features

Revision ID: 93bca7881762
Revises: 88a05ce91917
Create Date: 2026-05-15 16:59:11.041523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93bca7881762'
down_revision: Union[str, None] = '88a05ce91917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manifesto_promises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('councillor_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['councillor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manifesto_promises_councillor_id'), 'manifesto_promises', ['councillor_id'], unique=False)
    op.create_index(op.f('ix_manifesto_promises_id'), 'manifesto_promises', ['id'], unique=False)
    op.create_table('volunteer_badges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('volunteer_id', sa.UUID(), nullable=False),
    sa.Column('badge_name', sa.String(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volunteer_badges_id'), 'volunteer_badges', ['id'], unique=False)
    op.create_index(op.f('ix_volunteer_badges_volunteer_id'), 'volunteer_badges', ['volunteer_id'], unique=False)
    op.create_table('ward_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=False),
    sa.Column('resolution_score', sa.Float(), nullable=True),
    sa.Column('completion_rate', sa.Float(), nullable=True),
    sa.Column('volunteer_score', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ward_stats_id'), 'ward_stats', ['id'], unique=False)
    op.create_index(op.f('ix_ward_stats_ward_id'), 'ward_stats', ['ward_id'], unique=False)
    op.create_table('citizen_jury_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('verdict', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citizen_jury_reviews_complaint_id'), 'citizen_jury_reviews', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_citizen_jury_reviews_id'), 'citizen_jury_reviews', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_citizen_jury_reviews_id'), table_name='citizen_jury_reviews')
    op.drop_index(op.f('ix_citizen_jury_reviews_complaint_id'), table_name='citizen_jury_reviews')
    op.drop_table('citizen_jury_reviews')
    op.drop_index(op.f('ix_ward_stats_ward_id'), table_name='ward_stats')
    op.drop_index(op.f('ix_ward_stats_id'), table_name='ward_stats')
    op.drop_table('ward_stats')
    op.drop_index(op.f('ix_volunteer_badges_volunteer_id'), table_name='volunteer_badges')
    op.drop_index(op.f('ix_volunteer_badges_id'), table_name='volunteer_badges')
    op.drop_table('volunteer_badges')
    op.drop_index(op.f('ix_manifesto_promises_id'), table_name='manifesto_promises')
    op.drop_index(op.f('ix_manifesto_promises_councillor_id'), table_name='manifesto_promises')
    op.drop_table('manifesto_promises')
    # ### end Alembic commands ###
