"""upscale_features

Revision ID: aeb5b371cdc2
Revises: c6b56ba85ad7
Create Date: 2026-05-15 18:26:09.923242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeb5b371cdc2'
down_revision: Union[str, None] = 'c6b56ba85ad7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_kept', sa.Boolean(), nullable=True),
    sa.Column('councillor_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['councillor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promises_councillor_id'), 'promises', ['councillor_id'], unique=False)
    op.create_index(op.f('ix_promises_id'), 'promises', ['id'], unique=False)
    op.create_table('volunteer_badges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('volunteer_id', sa.UUID(), nullable=False),
    sa.Column('badge_name', sa.String(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volunteer_badges_id'), 'volunteer_badges', ['id'], unique=False)
    op.create_index(op.f('ix_volunteer_badges_volunteer_id'), 'volunteer_badges', ['volunteer_id'], unique=False)
    op.create_table('ward_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=False),
    sa.Column('resolution_score', sa.Float(), nullable=True),
    sa.Column('volunteer_turnout', sa.Integer(), nullable=True),
    sa.Column('month', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ward_stats_id'), 'ward_stats', ['id'], unique=False)
    op.create_index(op.f('ix_ward_stats_ward_id'), 'ward_stats', ['ward_id'], unique=False)
    op.create_table('citizen_juries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('verdict', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citizen_juries_id'), 'citizen_juries', ['id'], unique=False)
    op.add_column('volunteers', sa.Column('reputation_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteers', 'reputation_score')
    op.drop_index(op.f('ix_citizen_juries_id'), table_name='citizen_juries')
    op.drop_table('citizen_juries')
    op.drop_index(op.f('ix_ward_stats_ward_id'), table_name='ward_stats')
    op.drop_index(op.f('ix_ward_stats_id'), table_name='ward_stats')
    op.drop_table('ward_stats')
    op.drop_index(op.f('ix_volunteer_badges_volunteer_id'), table_name='volunteer_badges')
    op.drop_index(op.f('ix_volunteer_badges_id'), table_name='volunteer_badges')
    op.drop_table('volunteer_badges')
    op.drop_index(op.f('ix_promises_id'), table_name='promises')
    op.drop_index(op.f('ix_promises_councillor_id'), table_name='promises')
    op.drop_table('promises')
    # ### end Alembic commands ###
