"""add_location_address

Revision ID: c6b56ba85ad7
Revises: 93bca7881762
Create Date: 2026-05-15 18:06:55.227724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6b56ba85ad7'
down_revision: Union[str, None] = '93bca7881762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manifesto_promises_councillor_id'), table_name='manifesto_promises')
    op.drop_index(op.f('ix_manifesto_promises_id'), table_name='manifesto_promises')
    op.drop_table('manifesto_promises')
    op.drop_index(op.f('ix_citizen_jury_reviews_complaint_id'), table_name='citizen_jury_reviews')
    op.drop_index(op.f('ix_citizen_jury_reviews_id'), table_name='citizen_jury_reviews')
    op.drop_table('citizen_jury_reviews')
    op.drop_index(op.f('ix_volunteer_badges_id'), table_name='volunteer_badges')
    op.drop_index(op.f('ix_volunteer_badges_volunteer_id'), table_name='volunteer_badges')
    op.drop_table('volunteer_badges')
    op.drop_index(op.f('ix_ward_stats_id'), table_name='ward_stats')
    op.drop_index(op.f('ix_ward_stats_ward_id'), table_name='ward_stats')
    op.drop_table('ward_stats')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ward_stats',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ward_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resolution_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('completion_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('volunteer_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], name=op.f('ward_stats_ward_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ward_stats_pkey'))
    )
    op.create_index(op.f('ix_ward_stats_ward_id'), 'ward_stats', ['ward_id'], unique=False)
    op.create_index(op.f('ix_ward_stats_id'), 'ward_stats', ['id'], unique=False)
    op.create_table('volunteer_badges',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('volunteer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('badge_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('earned_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], name=op.f('volunteer_badges_volunteer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('volunteer_badges_pkey'))
    )
    op.create_index(op.f('ix_volunteer_badges_volunteer_id'), 'volunteer_badges', ['volunteer_id'], unique=False)
    op.create_index(op.f('ix_volunteer_badges_id'), 'volunteer_badges', ['id'], unique=False)
    op.create_table('citizen_jury_reviews',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('complaint_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('verdict', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('citizen_jury_reviews_complaint_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('citizen_jury_reviews_pkey'))
    )
    op.create_index(op.f('ix_citizen_jury_reviews_id'), 'citizen_jury_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_citizen_jury_reviews_complaint_id'), 'citizen_jury_reviews', ['complaint_id'], unique=False)
    op.create_table('manifesto_promises',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('councillor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('deadline', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['councillor_id'], ['users.id'], name=op.f('manifesto_promises_councillor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('manifesto_promises_pkey'))
    )
    op.create_index(op.f('ix_manifesto_promises_id'), 'manifesto_promises', ['id'], unique=False)
    op.create_index(op.f('ix_manifesto_promises_councillor_id'), 'manifesto_promises', ['councillor_id'], unique=False)
    # ### end Alembic commands ###
